### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-ospo/ospo.berkeley.edu#23]
- [ ] Use ospo.berkeley.edu 
- [x] Update usospo.net and link to ospo.berkeley.edu
- [x] Link to usospo.net blog
- [ ] Add grants / projects
- [ ] Form campus committee (library, campus IT, departmental IT, faculty, post-doc, graduate, undergraduate)
  - [ ] Charter / purpose
  - [ ] Recruit
  - [ ] Monthly meetings?

**Comment by jarrodmillman** [comment]
- [ ] https://www.ocf.berkeley.edu/
- [ ] https://opensource.berkeley.edu/
- [ ] http://berkeleybop.org/
- [ ] https://www.berkeleysciencereview.com/
- [ ] https://ccb.berkeley.edu/outreach/workshops-and-bootcamps
- [ ] https://calnerds.berkeley.edu/ & https://star.berkeley.edu/
- [ ] https://berkeley.libcal.com/calendar/workshops/UCC2024R1
- [ ] https://dlab.berkeley.edu/
- [ ] https://people.eecs.berkeley.edu/~istoica/
- [ ] https://infwinston.github.io/
- [ ] https://cto.berkeley.edu/home/welcome-cto-bill-allison
- [ ] https://ipira.berkeley.edu/open-source-software-startup-good-standing-agreement
- [ ] https://ipira.berkeley.edu/people/mike-cohen
- [ ] https://people.eecs.berkeley.edu/~bh/
- [ ] https://www.lib.berkeley.edu/help/staff-directory/anna-sackmann
- [ ] https://www.lib.berkeley.edu/help/staff-directory/timothy-vollmer
- [ ] https://rtl.berkeley.edu/academic-innovation-studio-ais
- [ ] https://macss.berkeley.edu/
- [ ] https://cdss.berkeley.edu/people/eric-van-dusen

**Comment by jarrodmillman** [comment]
- [ ] https://openaccess.unt.edu/unt-open-access-policy
- [ ] https://sparcopen.org/coapi/
- [ ] https://github.com/nlharris
- [ ] https://github.com/caufieldjh
- [ ] https://www.math.ucdavis.edu/~mkoeppe/
